export const MainPageActionTypes = {
  INCREMENT_SHOWING_FILMS: `INCREMENT_SHOWING_FILMS`,
};

export const GenresListActionTypes = {
  CHANGE_GENRE_FILTER: `CHANGE_GENRE_FILTER`,
  RESET_SHOWING_FILMS: `RESET_SHOWING_FILMS`,
};

export const AppActionTypes = {
  SET_FILMS: `LOAD_FILMS`,
  SET_PROMO: `LOAD_PROMO`,
  SET_COMMENTS: `SET_COMMENTS`,
  SET_LOADED_STATUS: `SET_LOADED_STATUS`,
};

export const UserActionTypes = {
  REQUIRED_AUTHORIZATION: `REQUIRED_AUTHORIZATION`,
};
